"""The GuruFocus API catalogue, and the trap it exists to catch.

`stock/{sym}/<anything>` NEVER 404s. An unrecognised sub-path returns HTTP 200 and
a 46-point date-indexed series of zeros — indistinguishable, at a glance, from a
real indicator. Probed naively, `stock/AAPL/news` and `stock/AAPL/splits` look like
working endpoints. They are not.

These tests are offline. They pin the classifier and the committed catalogue, so
that a future edit cannot quietly promote a fallback path into "an endpoint we can
build on". The catalogue itself is regenerated by
`scripts/gurufocus_catalog.py` (cached; a re-run costs no API calls).
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts.gurufocus_catalog import CANARY_PATH, _is_zero_series, classify

CATALOG = Path(__file__).resolve().parents[1] / "gurufocus_api.json"

# Real fallback payload shape, as returned for a nonsense sub-path.
FALLBACK = [["1980-09-28", 0], ["1981-09-28", 0], ["2025-09-28", 0]]


class TestZeroSeriesDetection:
    def test_all_zero_pairs_is_the_fallback(self):
        assert _is_zero_series(FALLBACK)

    def test_a_series_with_any_real_value_is_not(self):
        assert not _is_zero_series([["1980-09-28", 0], ["2025-09-28", -15421]])

    def test_floats_count_as_zero(self):
        assert _is_zero_series([["2024-01-01", 0.0], ["2025-01-01", 0]])

    @pytest.mark.parametrize("data", [None, [], {}, "x", [["a"]], [{"date": "x", "v": 0}]])
    def test_non_pair_shapes_are_not_the_fallback(self, data):
        """Only `[[date, number], …]` can be the fallback. A dict payload with zeros
        (e.g. a real `keyratios` response) must never be misread as one."""
        assert not _is_zero_series(data)


class TestClassify:
    def test_canary_path_is_labelled_canary(self):
        assert classify(CANARY_PATH, FALLBACK, FALLBACK) == "canary"

    def test_payload_identical_to_the_canary_is_a_fallback(self):
        assert classify("stock/AAPL/news", FALLBACK, FALLBACK) == "router-fallback"

    def test_zero_series_is_a_fallback_even_if_the_canary_failed_to_load(self):
        """Belt and braces: a false 'real' here becomes an endpoint someone builds on."""
        assert classify("stock/AAPL/splits", FALLBACK, None) == "router-fallback"

    def test_no_data_is_missing(self):
        assert classify("stock_list", None, FALLBACK) == "missing"

    def test_empty_container_is_empty_not_real(self):
        """`cusip/<an ISIN>` returns `[]` — the endpoint exists, the input didn't match."""
        assert classify("cusip/US0378331005", [], FALLBACK) == "empty"

    def test_a_genuinely_different_payload_is_real(self):
        assert classify("stock/AAPL/dividend", [{"amount": "0.27"}], FALLBACK) == "real"

    def test_a_non_degenerate_series_is_real(self):
        assert classify("stock/AAPL/dividends", [["2025-09-28", -15421]], FALLBACK) == "real"


@pytest.mark.skipif(not CATALOG.exists(), reason="run scripts/gurufocus_catalog.py first")
class TestCommittedCatalogue:
    @pytest.fixture(scope="class")
    def by_path(self) -> dict[str, dict]:
        return {f["path"]: f for f in json.loads(CATALOG.read_text(encoding="utf-8"))}

    @pytest.mark.parametrize("path", [
        "isin/US0378331005",
        "isin/AT0000730007",
        "exchange_list",
        "cusip/037833100",
        "stock/AAPL/summary",
        "stock/AAPL/financials",
        "stock/AAPL/dividend",
        "stock/AAPL/analyst_estimate",
        "stock/AAPL/price",
    ])
    def test_endpoints_we_depend_on_are_real(self, by_path, path):
        assert by_path[path]["verdict"] == "real", path

    @pytest.mark.parametrize("path", [
        "stock/AAPL/split", "stock/AAPL/splits", "stock/AAPL/analyst_estimates",
        "stock/AAPL/guru", "stock/AAPL/news", "stock/AAPL/segments",
        "stock/AAPL/profile", "stock/AAPL/valuation", "stock/AAPL/rank",
        "stock/AAPL/earnings", "stock/AAPL/indicator_price",
    ])
    def test_known_fallbacks_stay_marked_fake(self, by_path, path):
        """If one of these ever flips to `real`, GuruFocus shipped a new endpoint —
        verify it by hand before using it. It is far more likely someone hand-edited
        the catalogue."""
        assert by_path[path]["verdict"] == "router-fallback", path

    def test_the_singular_dividend_is_per_share_and_the_plural_is_not(self):
        """`dividend` -> per-payment records (amount per share). `dividends` -> the
        cash-flow-for-dividends indicator, in $ millions and NEGATIVE. Using the
        plural as a per-share series is the mistake this catalogue prevents."""
        assert "amount" in by_path_item(CATALOG, "stock/AAPL/dividend")["item_keys"]
        plural = by_path_item(CATALOG, "stock/AAPL/dividends")
        assert plural["verdict"] == "real"
        assert plural["item_keys"] == []          # [[date, value]] pairs, not dicts

    def test_catalogue_never_contains_the_api_key(self):
        """The probe URLs embed the key; only the path may be committed."""
        text = CATALOG.read_text(encoding="utf-8")
        assert "public/user" not in text


def by_path_item(catalog: Path, path: str) -> dict:
    for f in json.loads(catalog.read_text(encoding="utf-8")):
        if f["path"] == path:
            return f
    raise KeyError(path)
