'use client';

import { useLang, type Lang } from '../../../lib/i18n';

/** Copy for the primary Analyse view. Child dialogs own their copy separately. */
const en = {
  lang: 'en',
  actions: {
    close: 'Close', refresh: 'Refresh', refreshing: 'Refreshing…', cancel: 'Cancel',
    cancelling: 'Cancelling…', attribution: 'Attribution', risk: 'Risk', fundamental: 'Fundamental',
    cancelRefresh: 'Cancel this refresh', refreshPortfolio: 'Refresh this portfolio',
    cancellingTitle: 'Cancelling — the account being downloaded finishes first.',
    columns: '+ columns', columnsTitle: 'Show the columns behind each figure',
    lookThrough: 'Look through certificates',
    lookThroughTitle: 'A holding that is itself another portfolio is listed as its underlying instruments. Untick to fold it back into one row naming the strategy. Class subtotals, charts, and totals remain identical because the fold stays within one asset class.',
  },
  columnGroups: {
    return: { label: 'How the Instrument return is built', hint: '(Value now − Beginwaarde) + Realised + Income = Result, ÷ Beginwaarde' },
    onmoney: { label: 'How Money-weighted is built', hint: 'Result ÷ Avg capital invested' },
    fxsplit: { label: 'Price vs currency (AIRS)', hint: 'Koers + Valuta + Rest = Result' },
    contribution: { label: 'How the Contribution is built', hint: 'Result ÷ the book’s opening capital' },
  },
  chrome: { benchmark: 'Benchmark', loading: 'Loading composition…', loadError: 'The composition could not be loaded.' },
  bucket: (name: string) => name,
  score: {
    returnYtd: 'Return (YTD) €', versusReturn: (benchmark: string) => `vs ${benchmark} return (YTD) €`, excess: 'Excess',
    portfolioWhat: 'What this portfolio returned year to date, in EUR.', portfolioNote: "the portfolio's return, year to date",
    /** ⚠ THE CAVEAT ONLY. `where` names AIRS Rendementen (ATT) and `note` names the field, so
     *  repeating both here was two thirds of a sentence the reader had already had — and it read
     *  as a derivation because it sat under "A formula on the data:". What is left is the part
     *  nothing else says: why a deposit does not flatter this number. */
    portfolioHowBook: 'Flow-aware and includes income, over the calendar year — a deposit does not flatter it.',
    portfolioHowModel: 'Σ(weightᵢ × returnᵢ) over the model’s holdings, each priced from its yfinance closes and converted to EUR at each date’s own rate, so the currency leg is included. Price return: dividends are not.',
    excessHint: "The portfolio's return minus the benchmark's, in percentage POINTS — the two figures to the left, subtracted. ⚠ It does NOT equal the Attribution table's total: that decomposes the index constituent by constituent, so it reconciles to the rebuilt index rather than to the ETF figure shown here.",
    attributionTitle: 'Why? — break the excess into allocation vs selection (Brinson-Fachler attribution).',
    riskTitle: 'Risk — how far the stock sleeve sits from the benchmark (active share), and how much that difference has actually moved (realised tracking error).',
  },
  allocation: {
    title: 'Allocation', filtering: 'Filtering to', showAll: '— show all ✕', filterHint: 'Click a class to filter the charts',
    minimum: 'minimal', target: 'target', maximum: 'maximal', sold: 'Sold during the year — no longer a holding',
    portfolio: 'Portfolio', of: 'of', nothing: 'Nothing to show — the current selection holds no equity, and sector is an equity-only view.',
    unpriceable: (pct: string) => `${pct}% held but unpriceable — missing from these bars`,
    excludes: (pct: string, axis: string) => `Excludes ${pct}% in funds, bonds and cash — no ${axis} to place`,
    policyTitle: (variant: string) => `Read from this model's own AIRS name. The bands drawn over the bars are the ${variant} allocation policy.`,
    unpricedTitle: 'Real holdings, in real buckets, that we have no price series for. They are absent from the bars, so the buckets they belong to read lower than they are. The holdings table below names them, and the Resolved column on the portfolio row counts them.',
    excludedTitle: 'Funds, bonds and cash have no sector of their own — they are their own slices of the allocation chart above, and the holdings table below names them.',
    totalsTitle: 'Each column is summed exactly as printed, so adding the rows by hand gives this number. Both sides are renormalised over the holdings they can place.',
    rowTitle: (bucket: string, pct: string, holdings: number, ret: string | null) => `${bucket} — ${pct}% of the portfolio${holdings ? `, ${holdings} holding${holdings === 1 ? '' : 's'}` : ''}${ret ? `, ${ret} YTD` : ''}`,
    contributionTitle: (bucket: string, contribution: string, ret: string) => `${bucket} added ${contribution} to the book’s year. Its own return was ${ret} — a rate on its own opening value, which is why the two differ and why only this one adds up.`,
    chartRowTitle: (bucket: string, portfolio: string, benchmark: string, benchmarkValue: string, tilt: string) => `${bucket} · Portfolio ${portfolio}% vs ${benchmark} ${benchmarkValue}% · tilt ${tilt}pp`,
  },
  axes: {
    sector: 'Sector', region: 'Region', currency: 'Currency',
    sectorNote: 'Start-of-window weights. Cash, funds and unpriced holdings have no sector.',
    regionNote: "The issuer's domicile, else its ISIN country. Not the listing venue.",
    currencyNote: 'The reporting currency of the company. Not the listing currency.',
  },
  holdings: {
    title: 'Holdings', name: 'Name', via: 'Via', sector: 'Sector', momentum: 'Momentum', vol: 'Volatility', beta: 'Beta',
    weightNow: 'Weight (now)', opening: 'Beginwaarde (1 Jan)', valueNow: 'Value now', avgCapital: 'Avg capital invested',
    unrealised: 'Unrealised', realised: 'Realised', income: 'Income', result: 'Result', price: 'Koers', currency: 'Valuta',
    rest: 'Rest', moneyWeighted: 'Money-weighted', instrumentReturn: 'Instrument return', contribution: 'Contribution',
    noValues: 'No valued positions to show here.', noSector: 'No sector — a fund, or not classifiable',
    noLongerHeld: 'No longer held', soldOut: 'sold out during the year', priorYear: 'prior yr',
    bookYear: 'The book’s year', allPositions: 'positions, everything it held or sold', direct: 'direct',
  },
  info: {
    holdingsWhat: 'Every instrument the portfolio holds, grouped by asset class. A position held through a certificate is listed as the instruments behind it, not as the certificate.',
    viaWhat: 'How the portfolio got into this instrument — its own shares, a strategy whose certificate was looked through to reach it, or both.',
    sectorWhat: 'The sector this instrument is counted in on the Sector chart above.',
    momentumWhat: "12-1 momentum: the last 12 months' EUR return, excluding the most recent month.",
    momentumNote: 'signal_engine mom_12_1 — the same one /signal-lab charts',
    volWhat: "How much this instrument's price moves, annualised, over the last 5 years.",
    volNote: 'annualised standard deviation of monthly EUR returns',
    volHeaderHow: (example: string) => `std(monthly return, ddof=1) × √12 over the trailing 5 years of our own yfinance closes, converted to EUR at each date's rate.${example}\n\nUnder four years of history shows a dash, not a zero.`,
    betaWhat: (benchmark: string) => `How much this instrument moves for each 1% of ${benchmark}, over 5 years.`,
    betaNote: (benchmark: string) => `weekly EUR returns, regressed on ${benchmark}`,
    betaHeaderHow: (benchmark: string, example: string) => `cov(instrument, ${benchmark}) ÷ var(${benchmark}), using weekly EUR returns over the trailing 5 years against ${benchmark}'s investable tracker, on the dates both series have.${example}\n\nToo little overlapping history shows a dash, not a zero.`,
    weightWhat: 'The share of the portfolio held in this instrument, right now.',
    openingWhat: 'What this position was worth at the start of the year, on AIRS’s own basis.',
    valueNowWhat: 'What this position is worth today.',
    avgCapitalWhat: 'The money actually tied up in this position over the year.',
    unrealisedWhat: 'What this position has gained or lost while the book has held it — on paper, not banked.',
    unrealisedNote: 'value now − value when the year opened',
    realisedWhat: 'What was banked by actually selling — this year’s part of it.',
    realisedNote: 'AIRS’s Res. YtD, summed over the year’s sales',
    incomeWhat: 'The dividends and coupons this position paid the book this year.', incomeNote: 'net — gross less withholding tax',
    resultWhat: 'What the book actually made on this position this year, in euros.', resultNote: 'unrealised + realised + income',
    priceWhat: "How much of the result is the instrument's own price move, with the currency taken out.",
    priceNote: "AIRS's Fondsresultaat, in EUR",
    priceHow: (total: string) => `AIRS splits every held position's value change into a price leg and a currency leg, both in euros, and publishes both. This is its reported Fondsresultaat; nothing is re-derived here.\n\nΣ = ${total}\n\n⚠ It covers only the held leg. Fondsresultaat + Valutaresultaat = Value now − Beginwaarde, so realised sales and dividends sit outside the pair in Rest.\n\n⚠ The second line expresses the same euros as points of this row's money-weighted return, using the same average invested capital. Koers + Valuta + Rest therefore add exactly to that return.\n\n⚠ These are points, not shares of the return. Opposing legs make a share unbounded and sign-flipping.\n\n⚠ A subtotal shows points only when every underlying row has both the split and invested capital. The grand total never shows them because its Result includes sold positions without a split.`,
    currencyWhat: 'How much of the result is the exchange rate moving, with the price taken out.', currencyNote: "AIRS's Valutaresultaat, in EUR",
    currencyHow: (total: string) => `AIRS's Valutaresultaat as reported.\n\nΣ = ${total}\n\n⚠ A euro holding reads 0, and that is a measurement rather than a gap. A blank means AIRS published no split: cash, a leg inside a certificate, or a snapshot before 2026-07-18.\n\n⚠ The price and currency legs routinely pull against each other; the net result can therefore be much smaller than either leg.`,
    restWhat: "The part of the result AIRS's price/currency split does not reach.", restNote: 'result − koers − valuta',
    restHow: (total: string) => `Result − Koers − Valuta\n\n= ${total}\n\n⚠ In practice this is the realised leg and dividends. AIRS splits what is held; its transactions sheet has no currency column and dividends are booked in EUR. A book that trimmed therefore has a remainder while a book that only held may have none.\n\n⚠ It is derived by subtraction and consequently absorbs any gap between AIRS's split and our held result. Three columns that add to Result are checkable; two that fall short look like an error.`,
    contributionWhat: 'What this position added to, or took off, the book’s return for the year.',
    contributionNote: 'result ÷ the book’s opening capital', moneyNote: 'result ÷ average invested capital',
    moneyWhat: 'What this position returned on the money actually put into it — a money-weighted return (Modified Dietz), so WHEN you bought and sold is part of the answer.',
    instrumentWhat: (anchor: string) => `What this instrument itself returned in euros since ${anchor} — independent of how much of it the book holds, and independent of when you traded it.`,
    instrumentHow: (example: string) => `(Huidige waarde + net income) ÷ Beginwaarde − 1, per row${example}\n\nBeginwaarde prices today's share count at its 1 January price, which removes your timing. This is therefore not a chained time-weighted return: a share bought in June is still measured from January. Money-weighted beside it uses the same Result over the capital actually tied up.\n\nA row marked ƒ uses our own EUR price series instead. Class rows divide their own Result by their own Beginwaarde.`,
    soldMoneyWhat: 'What the positions sold out during the year returned on the money put into them.',
    soldContributionWhat: 'What the positions sold out during the year added to, or took off, the book’s return.',
    bookMoneyWhat: 'What the book returned on the money it actually had at work — over the positions whose purchases and sales we can see.',
    bookReturnWhat: 'The book’s own return for the year, from AIRS.',
    bookReturnNote: 'cumulatief_rendement — flow-aware, the system of record',
    bookContributionWhat: 'What every position in this table, held and sold, added up to for the book’s year.', yearOpened: 'the year opened',
    holdingsHow: (rows: number, through: number) => `one row per ISIN, after the certificates are looked through\n\n${rows} rows, ${through} of them reached through a certificate`,
    /**
     * ⚠⚠ THE LIVE COUNT LIVES IN `viaNote`, WHICH RENDERS ON THE **Where** LINE (2026-09-01,
     * on request: 'the how should be really simple here'). It used to be a second paragraph
     * inside `viaHow`, so the field answering HOW THE NUMBER IS MADE carried a live measurement
     * of THIS book — a Where fact. The house style already puts live figures in `where`; this
     * was the one card that had them in `how`.
     */
    viaNote: (through: number, rows: number) => `${through} of ${rows} rows arrive through a certificate, the rest are held outright`,
    viaHow: 'each route’s share of the book — they sum to that row’s Weight',
    sectorHow: (sectors: number, classified: number, missing: number) => `Yahoo’s sector for the ISIN, canonicalised so one sector has one name\n\n${sectors} sectors across ${classified} rows; ${missing} have none (a fund, or unclassifiable)`,
    momentumHow: (example: string) => `Price one month ago ÷ price twelve months ago − 1${example}`,
    weightHow: (rows: number, total: string) => `Huidige waarde ÷ the book’s total Huidige waarde\n\nthe ${rows} rows below sum to ${total} = 100.00%`,
    openingHow: (total: string) => `Σ (quantity held today × its price on 1 January)\n\n= ${total}`,
    valueNowHow: (total: string) => `Σ (AIRS’s current valuation)\n\n= ${total}`,
    avgCapitalHow: (total: string) => `Σ (value at the open + each flow × the share of the year still to run)\n\n= ${total}`,
    unrealisedHow: (now: string, opening: string, result: string) => `Value now − Beginwaarde\n\n${now} − ${opening} = ${result}`,
    realisedHow: (total: string) => `Σ Res. YtD over the year’s sales\n\n= ${total}`,
    incomeHow: (total: string) => `Σ (dividend + withholding tax)\n\n= ${total}`,
    resultHow: (unrealised: string, realised: string, income: string, result: string) => `Unrealised + Realised + Income\n\n${unrealised} + ${realised} + ${income} = ${result}`,
    moneyHow: (result: string, capital: string, pct: string) => `Result ÷ Avg capital invested\n\n${result} ÷ ${capital} = ${pct}`,
    contributionHow: (result: string, basis: string, pct: string) => `Result ÷ the book’s opening capital\n\n${result} ÷ ${basis} = ${pct}`,
  },
  sleeve: { noPrices: (bucket: string) => `No priced holdings in ${bucket}`, performance: 'Performance', currency: 'Currency' },
  row: {
    thisPosition: 'This position', thisHolding: 'This holding', noSector: 'No sector — a fund, or not classifiable',
    momentumNote: 'signal_engine mom_12_1, EUR', volNote: 'annualised standard deviation of monthly EUR returns',
    momentumMissing: 'A dash is not a zero — 0% would claim it went nowhere. Needs about 13 months of price history; the two risk columns beside it need four years, so a young listing can show momentum and a dash for volatility.',
    momentumMissingWhat: (name: string) => `${name} has under about 13 months of price history, so it has no 12-1 momentum.`,
    momentumWhat: (name: string) => `What ${name} returned over the 12 months ending one month ago.`,
    // ⚠ THE POPULATION IS IN THE SENTENCE. A rank without its reference set is unreadable — "82nd"
    //   of what, out of how many? — and the chip is glyphs, so this is the only place a reader can
    //   learn that `++` means a percentile against a named universe rather than a verdict.
    momentumRanked: (name: string, ordinal: string, benchmark: string, n: number) =>
      `What ${name} returned over the 12 months ending one month ago — the ${ordinal} strongest `
      + `percentile of the ${n.toLocaleString('en')} ${benchmark} members ranked on the same basis.`,
    momentumHow: (substitution: string) => `Price one month ago ÷ price twelve months ago − 1${substitution}\n\nThe most recent month is excluded on purpose: it mean-reverts, and including it is what makes a raw 12-month return a poor momentum signal.`,
    volHow: (pct: string) => `std(monthly return, ddof=1) × √12 = ${pct}\n\nOur own yfinance closes, converted to EUR at each date's rate — so the currency move is in it, which is what a euro holder actually bears.`,
    betaHow: (benchmark: string, beta: string) => `cov(instrument, ${benchmark}) ÷ var(${benchmark}) = ${beta}\n\nWeekly EUR returns over the trailing 5 years, on the weeks both series have — weekly because the benchmark tracker and a US listing close five hours apart, which halves a daily correlation.`,
    volMissing: 'A dash is not a zero — 0.0% would read as remarkably stable.',
    betaMissing: 'A dash is not a zero — 0 would claim it moves independently of the market.',
    volMissingWhat: (name: string) => `${name} has under four years of price history, so it has no five-year volatility.`,
    volWhat: (name: string) => `How much ${name}'s price moves, annualised, over the last 5 years.`,
    betaMissingWhat: (name: string, benchmark: string) => `${name} has too little overlapping history with ${benchmark} to measure a beta.`,
    betaWhat: (name: string, benchmark: string) => `How much ${name} moves for each 1% of ${benchmark}.`,
    betaNote: (benchmark: string) => `weekly EUR returns vs ${benchmark}, 5 years`,
    weightWhat: (name: string) => `${name}'s share of the book TODAY.`,
    weightNote: 'Huidige waarde ÷ the book’s total Huidige waarde',
    yfFallback: 'yfinance, not AIRS — no AIRS book values this row (its wrapped model has no paired account, or it has no opening value anywhere), so there is no book figure to show.',
    interpolated: "Opening price interpolated — no close near the window's start",
    noEndValue: 'no valuation at one end of the window — a dash, never a 0%, because “could not price” and “did not move” are different facts',
    priorYear: (value: string) => `${value} of this position's realised result was earned in EARLIER years and is correctly not in this year's figure.`,
    moneyLookthroughWhat: (book: string, name: string) => `What ${book} made on the money it put into ${name}; this book holds it through a certificate.`,
    moneyDirectWhat: (name: string) => `What ${name} returned on the money actually put into it.`,
    moneyViaWhat: (certificate: string) => `Held through ${certificate}, which has the purchases; this leg has none of its own.`,
    moneyCashWhat: 'Cash is not bought and sold, so there is no invested capital to measure against.',
    moneyUnknownWhat: (name: string) => `What ${name} returned on the money put into it cannot be worked out.`,
    lookthroughHow: (book: string, capital: string, pct: string, name: string, certificate: string, slice: string) => `Result ÷ Avg capital invested, measured in ${book}\n\n${capital} of average invested capital there → ${pct}\n\nThis book bought ${certificate}, not ${name}. This is what ${book} made on its own money. Your timing into the certificate is excluded. The ${slice} beside it is your slice of the position; scaling both sides leaves the rate unchanged.`,
    noTransactionsHow: (reason: string) => `Result ÷ Avg capital invested\n\nno denominator — ${reason} Nothing is wrong with this position; every other column is unaffected.`,
    depositedHow: 'Result ÷ Avg capital invested\n\nrefused — shares were deposited during the year (split, bonus issue, or transfer in), so trade and holding quantities use different bases and invested capital cannot be derived. Euro columns are unaffected.',
    viaHow: (name: string, certificate: string, routes: string, pct: string, capital: string) => `Result ÷ Avg capital invested\n\nno denominator for ${name}: AIRS trades ${certificate}${routes} rather than its underlying instruments, so this leg has no purchases.\n\nThe certificate can be measured: ${pct} on ${capital} average invested capital. That is one figure for the wrapper, not this stock's own.`,
    cashHow: 'Result ÷ Avg capital invested\n\ndoes not apply — cash is not bought and sold. Its return is 0% by construction and its drag is already in the class and book totals.',
    genericNoCapitalHow: 'Result ÷ Avg capital invested\n\nno denominator — this position is reached through a certificate that AIRS trades instead of the underlying instruments.',
    returnMissingWhat: (name: string) => `${name} could not be priced over this window.`,
    returnWhat: (name: string, from: string) => `What ${name} returned since ${from}, in EUR.`,
    yfReturnNote: 'our own EUR close series — no AIRS book values this row',
    contributionMissingWhat: (name: string) => `${name} has no result to contribute because it could not be valued over the window.`,
    contributionWhat: (name: string) => `What ${name} added to, or took off, the book’s return for the year.`,
    noContributionHow: 'Result ÷ the book’s opening capital\n\nno result — the position could not be valued at both ends of the window, so there is nothing to divide',
    weightHow: (value: string, total: string, pct: string) => `Huidige waarde ÷ the book’s total Huidige waarde\n\n${value} ÷ ${total} = ${pct}`,
    fundamentalTitle: (name: string) => `Fundamental — is ${name} fundamentally good? (owner earnings + price steadiness)`,
    timingTitle: (name: string) => `Why the trading mattered for ${name}`,
    heldDirectly: 'held directly', atOpen: 'at the open', netDividend: 'net dividend',
    strategyBehindCertificate: 'the strategy behind the certificate', certificate: 'a certificate',
    childBook: 'the child book', theCertificate: 'the certificate',
    noTransactions: 'this book has no readable transactions, so there are no flows to weigh the capital by.',
    soldRiskPrice: (isin: string) => `No price series is stored for ${isin}, so this instrument's risk figures cannot be computed.`,
    soldRiskIdentity: (name: string) => `Could not resolve “${name}” to an ISIN. It is no longer held by a book with a snapshot and has no pinned identity, so there is no instrument to measure.`,
    blendNote: (count: number) => `${count} routes in, each valued by the book that holds it, weighted by opening value`,
    blendHow: (math: string) => `Σ (each route’s share of this position × that route’s own return)\n\n${math}`,
    yfReturnHow: (pct: string, from: string) => `our own EUR close series — no AIRS book values this row\n\n${pct} since ${from}`,
    bookReturnHow: (math: string, pct: string, valuedBy?: string) => `(Huidige waarde + net income) ÷ Beginwaarde − 1${valuedBy ? `, as valued by ${valuedBy}` : ''}\n\n${math} = ${pct}`,
    routeTitle: (label: string, bookPct: string, value: string, rowPct?: string) => `${label}: ${bookPct}% of the book · ${value}${rowPct ? ` · ${rowPct}% of this position` : ''}`,
  },
  classRow: {
    fundamentalTitle: (count: number, bucket: string) => `Blended owner earnings and price steadiness across the ${count} priced name${count === 1 ? '' : 's'} in ${bucket}, weighted by what the book holds today.`,
    weightWhat: (bucket: string) => `${bucket}'s share of the book TODAY.`,
    chartWeightNote: 'the allocation chart’s own figure — cash included', rowsWeightNote: 'summed from the rows below',
    moneyWhat: (bucket: string) => `What ${bucket} returned on the money actually put into it.`,
    coverageTitle: (pct: string, bucket: string, missing: number) => `This rate covers ${pct}% of what ${bucket} made. ${missing} position(s) had no value when the year opened, so their result has no return denominator. Their euros remain in Result.`,
    noReturn: (bucket: string) => `Nothing in ${bucket} was held when the year opened, so it has no return to measure.`,
    returnWhat: (bucket: string) => `What ${bucket} made this year against its value when the year opened.`,
    contributionWhat: (bucket: string) => `What ${bucket} added to, or took off, the book’s return for the year.`,
    dashNote: 'a dash, never 0% — “no starting money to measure against” and “went nowhere” are different facts',
    moneyHow: (result: string, capital: string, pct: string, covered: number, total: number) => `Result ÷ Avg capital invested\n\n${result} ÷ ${capital} = ${pct}${covered < total ? ` (over ${covered} of ${total} holdings the book buys and sells itself; the rest sit inside certificates without their own flows)` : ''}`,
    returnHow: (result: string, opening: string, pct: string) => `Result ÷ what this class was worth when the year opened\n\n${result} ÷ ${opening} = ${pct}`,
    returnNote: (result: string, opening: string, coverage?: string) => `${result} ÷ ${opening}${coverage ? ` · covers ${coverage}% of what this class made` : ''}`,
    contributionNote: (result: string) => `${result} ÷ the book’s opening capital`,
    contributionHow: (ret: string, share: string, opening: string, basis: string, contribution: string) => `Return × this class’s share of the book’s opening capital\n\n${ret} × ${share} (${opening} of ${basis}) = ${contribution}`,
    weightHow: (pct: string) => `Σ Huidige waarde of this class ÷ the book’s total\n\n${pct} — the same figure used by the Allocation bar above`,
  },
  sold: {
    soldOut: 'sold out during the year', priorYear: 'prior yr',
    moneyWhat: (name: string) => `What ${name} returned on the money put into it over the part of the year it was held.`,
    contributionWhat: (name: string) => `What ${name} added to, or took off, the book’s return before it was sold.`,
    momentumTitle: (name: string) => `12-1 momentum for ${name}, as of today rather than the sale date, on the same basis as held rows.`,
    volTitle: (name: string) => `Five-year annualised volatility of ${name} in EUR, as of today.`,
    betaTitle: (name: string, benchmark: string) => `Five-year beta of ${name} against ${benchmark}, using weekly EUR returns.`,
  },
  reconciliation: {
    positions: (count: number) => `${count} positions, everything it held or sold`,
    compareHow: (contribution: string, book: string, agrees: boolean) => `AIRS's own cumulatief_rendement against the Contribution total\n\n${contribution} from these rows vs ${book} from AIRS — they ${agrees ? 'agree' : 'do NOT agree'}`,
    success: (book: string) => `✓ These positions account for the whole year — Contribution adds exactly to AIRS's ${book}.`,
    mismatch: (sum: string, book: string, residual: string) => `⚠ Contribution adds to ${sum} against AIRS's ${book}; ${residual} of the year is not explained by these rows.`,
  },
  /* ⚠⚠ IT NAMES THE COUNTRIES, AND THE OLD COPY NAMED THE WRONG CAUSE. It used to say "the rest
     have no price series yet" — measured on ACWI, exactly ONE of the members that reach the price
     world lacks a series. The real gap is the ISIN bridge, and it is not spread evenly: **India is
     2 priced of 161**, the UK 41 of 72, Hong Kong 152 of 182, while the United States is 474 of
     ~476 and Canada and Australia are whole. "Treat the tilts as indicative" told a reader the
     index was a bit noisy; what they were actually looking at was an ACWI with India removed, and
     the REGIONAL tilt against it is not approximate but wrong in a nameable direction.
     ⚠ `missing` is empty when the server could not work out the breakdown — the sentence then
     stops after the count rather than claiming the gap is spread evenly. */
  coverageWarning: (priced: number, total: number, pct: string,
                    missing: { country: string; missing: number; members: number }[]) => {
    const head = `⚠ This index is rebuilt from ${priced} of its ${total} constituents (${pct}); weights are renormalised over the remainder.`;
    if (!missing.length) return `${head} Treat the tilts as indicative.`;
    const where = missing.map((m) => `${m.country} (${m.members - m.missing} of ${m.members})`).join(', ');
    return `${head} The gap is NOT spread evenly — most of it is ${where}. Regional tilts against this benchmark are the least reliable part of the chart.`;
  },
  serverText: (text: string) => text,
} as const;

type Widen<T> = T extends (...args: infer A) => unknown ? (...args: A) => string
  : T extends string ? string : { -readonly [K in keyof T]: Widen<T[K]> };
export type AnalyseCopy = Widen<typeof en>;

const nl: AnalyseCopy = {
  lang: 'nl',
  actions: {
    close: 'Sluiten', refresh: 'Vernieuwen', refreshing: 'Vernieuwen…', cancel: 'Annuleren',
    cancelling: 'Annuleren…', attribution: 'Attributie', risk: 'Risico', fundamental: 'Fundamenteel',
    cancelRefresh: 'Deze vernieuwing annuleren', refreshPortfolio: 'Deze portefeuille vernieuwen',
    cancellingTitle: 'Annuleren — de rekening die nu wordt gedownload wordt eerst voltooid.',
    columns: '+ kolommen', columnsTitle: 'Toon de kolommen achter elk cijfer',
    lookThrough: 'Kijk door certificaten heen',
    lookThroughTitle: 'Een positie die zelf een andere portefeuille is wordt als de onderliggende instrumenten weergegeven. Vink dit uit om deze terug te vouwen tot één rij met de strategienaam. Subtotalen, grafieken en totalen blijven gelijk omdat alleen binnen dezelfde beleggingscategorie wordt gevouwen.',
  },
  columnGroups: {
    return: { label: 'Opbouw instrumentrendement', hint: '(Huidige waarde − Beginwaarde) + Gerealiseerd + Inkomsten = Resultaat, ÷ Beginwaarde' },
    onmoney: { label: 'Opbouw geldgewogen rendement', hint: 'Resultaat ÷ gemiddeld belegd kapitaal' },
    fxsplit: { label: 'Koers versus valuta (AIRS)', hint: 'Koers + Valuta + Rest = Resultaat' },
    contribution: { label: 'Opbouw bijdrage', hint: 'Resultaat ÷ beginkapitaal van het boek' },
  },
  chrome: { benchmark: 'Benchmark', loading: 'Samenstelling laden…', loadError: 'De samenstelling kon niet worden geladen.' },
  bucket: (name) => (({ Stocks: 'Aandelen', Bonds: 'Obligaties', Alternatives: 'Alternatieven', Cash: 'Liquiditeiten',
    Unclassified: 'Niet geclassificeerd' } as Record<string, string>)[name] ?? name),
  score: {
    returnYtd: 'Rendement (YTD) €', versusReturn: (benchmark) => `vs. rendement ${benchmark} (YTD) €`, excess: 'Meerrendement',
    portfolioWhat: 'Wat deze portefeuille sinds het begin van het jaar in euro heeft gerendeerd.', portfolioNote: 'het rendement van de portefeuille sinds het begin van het jaar',
    portfolioHowBook: 'Houdt rekening met stortingen en onttrekkingen en bevat inkomsten, over het kalenderjaar — een storting vleit dit cijfer dus niet.',
    portfolioHowModel: 'Σ(gewichtᵢ × rendementᵢ) over de posities van het model. Elke positie gebruikt yfinance-slotkoersen en wordt op elke datum tegen de eigen koers naar EUR omgerekend, zodat het valuta-effect is inbegrepen. Koersrendement: dividenden zijn uitgesloten.',
    excessHint: 'Het rendement van de portefeuille minus dat van de benchmark, in PROCENTPUNTEN — de twee cijfers links van elkaar afgetrokken. ⚠ Dit is NIET gelijk aan het totaal in de attributietabel: die ontleedt de index per constituent en sluit daarom aan op de herbouwde index in plaats van op het hier getoonde ETF-cijfer.',
    attributionTitle: 'Waarom? — splits het meerrendement uit in allocatie en selectie (Brinson-Fachler-attributie).',
    riskTitle: 'Risico — hoe ver het aandelendeel van de benchmark afwijkt (active share) en hoeveel die afwijking werkelijk heeft bewogen (gerealiseerde tracking error).',
  },
  allocation: {
    title: 'Allocatie', filtering: 'Filter op', showAll: '— alles tonen ✕', filterHint: 'Klik op een categorie om de grafieken te filteren',
    minimum: 'minimum', target: 'doel', maximum: 'maximum', sold: 'Verkocht gedurende het jaar — niet meer in portefeuille',
    portfolio: 'Portefeuille', of: 'van', nothing: 'Niets om te tonen — de huidige selectie bevat geen aandelen en sector is alleen voor aandelen.',
    unpriceable: (pct) => `${pct}% aangehouden maar niet prijsbaar — ontbreekt in deze balken`,
    excludes: (pct, axis) => `Exclusief ${pct}% in fondsen, obligaties en liquiditeiten — geen ${axis.toLowerCase()} om toe te wijzen`,
    policyTitle: (variant) => `Afgeleid uit de eigen AIRS-naam van dit model. De banden over de balken tonen het ${variant}-allocatiebeleid.`,
    unpricedTitle: 'Werkelijke posities in werkelijke categorieën waarvoor geen koersreeks beschikbaar is. Ze ontbreken in de balken, waardoor hun categorieën te laag lijken. De positietabel hieronder noemt ze en de kolom Opgelost op de portefeuillerij telt ze.',
    excludedTitle: 'Fondsen, obligaties en liquiditeiten hebben geen eigen sector — ze vormen eigen segmenten in de allocatiegrafiek hierboven en worden in de positietabel hieronder genoemd.',
    totalsTitle: 'Elke kolom is exact opgeteld zoals deze wordt weergegeven, zodat handmatig optellen hetzelfde getal oplevert. Beide zijden zijn herwogen over de posities die kunnen worden toegewezen.',
    rowTitle: (bucket, pct, holdings, ret) => `${bucket} — ${pct}% van de portefeuille${holdings ? `, ${holdings} positie${holdings === 1 ? '' : 's'}` : ''}${ret ? `, ${ret} YTD` : ''}`,
    contributionTitle: (bucket, contribution, ret) => `${bucket} droeg ${contribution} bij aan het boekjaar. Het eigen rendement was ${ret} — berekend over de eigen beginwaarde; daarom verschillen beide cijfers en telt alleen de bijdrage op.`,
    chartRowTitle: (bucket, portfolio, benchmark, benchmarkValue, tilt) => `${bucket} · Portefeuille ${portfolio}% versus ${benchmark} ${benchmarkValue}% · afwijking ${tilt}pp`,
  },
  axes: {
    sector: 'Sector', region: 'Regio', currency: 'Valuta',
    sectorNote: 'Wegingen aan het begin van de periode. Liquiditeiten, fondsen en niet-geprijsde posities hebben geen sector.',
    regionNote: 'Vestigingsland van de uitgevende instelling, anders het ISIN-land. Niet de plaats van notering.',
    currencyNote: 'Rapporteringsvaluta van de onderneming. Niet de noteringsvaluta.',
  },
  holdings: {
    title: 'Posities', name: 'Naam', via: 'Via', sector: 'Sector', momentum: 'Momentum', vol: 'Volatiliteit', beta: 'Bèta',
    weightNow: 'Gewicht (nu)', opening: 'Beginwaarde (1 jan)', valueNow: 'Huidige waarde', avgCapital: 'Gem. belegd kapitaal',
    unrealised: 'Ongerealiseerd', realised: 'Gerealiseerd', income: 'Inkomsten', result: 'Resultaat', price: 'Koers', currency: 'Valuta',
    rest: 'Rest', moneyWeighted: 'Geldgewogen', instrumentReturn: 'Instrumentrendement', contribution: 'Bijdrage',
    noValues: 'Geen gewaardeerde posities om hier te tonen.', noSector: 'Geen sector — een fonds of niet classificeerbaar',
    noLongerHeld: 'Niet meer aangehouden', soldOut: 'gedurende het jaar volledig verkocht', priorYear: 'vorig jaar',
    bookYear: 'Het boekjaar', allPositions: 'posities, alles wat is aangehouden of verkocht', direct: 'direct',
  },
  info: {
    holdingsWhat: 'Elk instrument dat de portefeuille aanhoudt, gegroepeerd naar beleggingscategorie. Een positie via een certificaat wordt weergegeven als de onderliggende instrumenten, niet als het certificaat.',
    viaWhat: 'Hoe de portefeuille in dit instrument terechtkwam — via eigen aandelen, via een strategie waarvan het certificaat is doorgelicht, of via beide.',
    sectorWhat: 'De sector waarin dit instrument in de sectorgrafiek hierboven wordt meegeteld.',
    momentumWhat: '12-1-momentum: het EUR-rendement over de laatste 12 maanden, exclusief de meest recente maand.',
    momentumNote: 'signal_engine mom_12_1 — dezelfde reeks die /signal-lab toont',
    volWhat: 'Hoe sterk de koers van dit instrument op jaarbasis bewoog over de laatste vijf jaar.',
    volNote: 'geannualiseerde standaarddeviatie van maandelijkse EUR-rendementen',
    volHeaderHow: (example) => `std(maandrendement, ddof=1) × √12 over de laatste vijf jaar van onze eigen yfinance-slotkoersen, op elke datum omgerekend naar EUR.${example}\n\nMinder dan vier jaar historie geeft een streepje, geen nul.`,
    betaWhat: (benchmark) => `Hoe sterk dit instrument over vijf jaar bewoog bij elke 1% beweging van ${benchmark}.`,
    betaNote: (benchmark) => `wekelijkse EUR-rendementen, geregresseerd op ${benchmark}`,
    betaHeaderHow: (benchmark, example) => `cov(instrument, ${benchmark}) ÷ var(${benchmark}), met wekelijkse EUR-rendementen over de laatste vijf jaar tegenover de verhandelbare tracker van ${benchmark}, op de datums die beide reeksen hebben.${example}\n\nTe weinig overlappende historie geeft een streepje, geen nul.`,
    weightWhat: 'Het huidige aandeel van dit instrument in de portefeuille.',
    openingWhat: 'De waarde van deze positie aan het begin van het jaar, op basis van AIRS.',
    valueNowWhat: 'De huidige waarde van deze positie.',
    avgCapitalWhat: 'Het kapitaal dat gedurende het jaar werkelijk in deze positie vastzat.',
    unrealisedWhat: 'Wat deze positie tijdens de aanhoudperiode op papier heeft gewonnen of verloren — nog niet verzilverd.',
    unrealisedNote: 'huidige waarde − waarde aan het begin van het jaar',
    realisedWhat: 'Wat door daadwerkelijke verkoop is verzilverd — het deel van dit jaar.',
    realisedNote: 'AIRS Res. YtD, opgeteld over de verkopen van dit jaar',
    incomeWhat: 'De dividenden en coupons die deze positie dit jaar aan het boek uitkeerde.', incomeNote: 'netto — bruto minus bronbelasting',
    resultWhat: 'Wat het boek dit jaar werkelijk in euro aan deze positie verdiende.', resultNote: 'ongerealiseerd + gerealiseerd + inkomsten',
    priceWhat: 'Het deel van het resultaat door de eigen koersbeweging van het instrument, zonder het valuta-effect.',
    priceNote: 'AIRS Fondsresultaat, in EUR',
    priceHow: (total) => `AIRS splitst de waardeverandering van elke aangehouden positie in een koersdeel en een valutadeel, beide in euro, en publiceert beide. Dit is het gerapporteerde Fondsresultaat; hier wordt niets opnieuw afgeleid.\n\nΣ = ${total}\n\n⚠ Dit dekt alleen het aangehouden deel. Fondsresultaat + Valutaresultaat = Huidige waarde − Beginwaarde. Gerealiseerde verkopen en dividenden vallen daarom buiten het paar en staan in Rest.\n\n⚠ De tweede regel drukt dezelfde euro's uit als punten van het geldgewogen rendement van deze rij, met hetzelfde gemiddeld belegde kapitaal. Koers + Valuta + Rest tellen daardoor exact op tot dat rendement.\n\n⚠ Dit zijn punten, geen aandelen van het rendement. Tegengestelde delen maken zo'n aandeel onbegrensd en laten het teken omslaan.\n\n⚠ Een subtotaal toont alleen punten wanneer elke onderliggende rij zowel de uitsplitsing als belegd kapitaal heeft. Het eindtotaal toont ze nooit, omdat Resultaat ook verkochte posities zonder uitsplitsing bevat.`,
    currencyWhat: 'Het deel van het resultaat door de wisselkoersbeweging, zonder het koerseffect.', currencyNote: 'AIRS Valutaresultaat, in EUR',
    currencyHow: (total) => `Het door AIRS gerapporteerde Valutaresultaat.\n\nΣ = ${total}\n\n⚠ Een europositie toont 0; dat is een meting en geen ontbrekend cijfer. Een lege waarde betekent dat AIRS geen uitsplitsing publiceerde: bij liquiditeiten, een onderliggende positie in een certificaat of een momentopname van vóór 18 juli 2026.\n\n⚠ Koers- en valutadelen werken regelmatig tegen elkaar in. Het nettoresultaat kan daardoor veel kleiner zijn dan elk afzonderlijk deel.`,
    restWhat: 'Het deel van het resultaat dat niet door AIRS’ koers-/valutaverdeling wordt gedekt.', restNote: 'resultaat − koers − valuta',
    restHow: (total) => `Resultaat − Koers − Valuta\n\n= ${total}\n\n⚠ In de praktijk zijn dit het gerealiseerde deel en dividenden. AIRS splitst wat nog wordt aangehouden; het transactiebestand heeft geen valutakolom en dividenden worden in EUR geboekt. Een boek dat heeft afgebouwd heeft daarom een rest, terwijl een boek dat alleen aanhield mogelijk geen rest heeft.\n\n⚠ Rest wordt door aftrekking afgeleid en neemt daardoor ook elk verschil op tussen AIRS' uitsplitsing en ons aangehouden resultaat. Drie kolommen die tot Resultaat optellen zijn controleerbaar; twee die tekortschieten lijken op een fout.`,
    contributionWhat: 'Wat deze positie aan het jaarrendement van het boek toevoegde of ervan aftrok.',
    contributionNote: 'resultaat ÷ beginkapitaal van het boek', moneyNote: 'resultaat ÷ gemiddeld belegd kapitaal',
    moneyWhat: 'Het rendement van deze positie op het werkelijk ingelegde geld — geldgewogen volgens Modified Dietz, zodat het moment van aan- en verkoop meetelt.',
    instrumentWhat: (anchor) => `Het EUR-rendement van het instrument zelf sinds ${anchor} — onafhankelijk van het portefeuillebelang en van het handelsmoment.`,
    instrumentHow: (example) => `(Huidige waarde + netto-inkomsten) ÷ Beginwaarde − 1, per rij${example}\n\nBeginwaarde waardeert het huidige aantal tegen de koers van 1 januari en verwijdert zo de eigen timing. Dit is daarom geen gekoppeld tijdgewogen rendement: een aandeel dat in juni is gekocht wordt nog steeds vanaf januari gemeten. Geldgewogen ernaast gebruikt hetzelfde Resultaat over het werkelijk belegde kapitaal.\n\nEen rij met ƒ gebruikt in plaats daarvan onze eigen EUR-koersreeks. Categorierijen delen hun eigen Resultaat door hun eigen Beginwaarde.`,
    soldMoneyWhat: 'Het rendement van de gedurende het jaar volledig verkochte posities op het daarin belegde geld.',
    soldContributionWhat: 'Wat de gedurende het jaar volledig verkochte posities aan het boekrendement toevoegden of ervan aftrokken.',
    bookMoneyWhat: 'Het rendement van het boek op het geld dat werkelijk aan het werk was — over de posities waarvan aankopen en verkopen zichtbaar zijn.',
    bookReturnWhat: 'Het eigen jaarrendement van het boek volgens AIRS.',
    bookReturnNote: 'cumulatief_rendement — kasstroomgewogen, het bronsysteem',
    bookContributionWhat: 'Wat alle aangehouden en verkochte posities in deze tabel samen aan het boekjaar bijdroegen.', yearOpened: 'het begin van het jaar',
    holdingsHow: (rows, through) => `één rij per ISIN, nadat door certificaten heen is gekeken\n\n${rows} rijen, waarvan ${through} via een certificaat zijn bereikt`,
    viaNote: (through, rows) => `${through} van de ${rows} rijen lopen via een certificaat; de rest wordt rechtstreeks aangehouden`,
    viaHow: 'het aandeel van elke route in het boek — samen vormen ze het Gewicht van die rij',
    sectorHow: (sectors, classified, missing) => `Yahoo’s sector bij het ISIN, gestandaardiseerd zodat elke sector één naam heeft\n\n${sectors} sectoren over ${classified} rijen; ${missing} hebben er geen (fonds of niet classificeerbaar)`,
    momentumHow: (example) => `Koers één maand geleden ÷ koers twaalf maanden geleden − 1${example}`,
    weightHow: (rows, total) => `Huidige waarde ÷ totale Huidige waarde van het boek\n\nde ${rows} rijen hieronder tellen op tot ${total} = 100,00%`,
    openingHow: (total) => `Σ (huidig aantal × koers op 1 januari)\n\n= ${total}`,
    valueNowHow: (total) => `Σ (huidige waardering volgens AIRS)\n\n= ${total}`,
    avgCapitalHow: (total) => `Σ (beginwaarde + elke kasstroom × resterend deel van het jaar)\n\n= ${total}`,
    unrealisedHow: (now, opening, result) => `Huidige waarde − Beginwaarde\n\n${now} − ${opening} = ${result}`,
    realisedHow: (total) => `Σ Res. YtD over de verkopen van dit jaar\n\n= ${total}`,
    incomeHow: (total) => `Σ (dividend + bronbelasting)\n\n= ${total}`,
    resultHow: (unrealised, realised, income, result) => `Ongerealiseerd + Gerealiseerd + Inkomsten\n\n${unrealised} + ${realised} + ${income} = ${result}`,
    moneyHow: (result, capital, pct) => `Resultaat ÷ gemiddeld belegd kapitaal\n\n${result} ÷ ${capital} = ${pct}`,
    contributionHow: (result, basis, pct) => `Resultaat ÷ beginkapitaal van het boek\n\n${result} ÷ ${basis} = ${pct}`,
  },
  sleeve: { noPrices: (bucket) => `Geen geprijsde posities in ${bucket}`, performance: 'Rendement', currency: 'Valuta' },
  row: {
    thisPosition: 'Deze positie', thisHolding: 'Deze positie', noSector: 'Geen sector — een fonds of niet classificeerbaar',
    momentumNote: 'signal_engine mom_12_1, EUR', volNote: 'geannualiseerde standaarddeviatie van maandelijkse EUR-rendementen',
    momentumMissing: 'Een streepje is geen nul — 0% zou beweren dat de koers niet bewoog. Hiervoor is ongeveer 13 maanden koershistorie nodig; de twee risicokolommen ernaast vereisen vier jaar. Een jonge notering kan daarom wel momentum maar geen volatiliteit tonen.',
    momentumMissingWhat: (name) => `${name} heeft minder dan ongeveer 13 maanden koershistorie en daarom geen 12-1-momentum.`,
    momentumWhat: (name) => `Het rendement van ${name} over de twaalf maanden die één maand geleden eindigden.`,
    momentumRanked: (name, ordinal, benchmark, n) =>
      `Het rendement van ${name} over de twaalf maanden die één maand geleden eindigden — het `
      + `${ordinal} sterkste percentiel van de ${n.toLocaleString('nl')} ${benchmark}-leden die op `
      + `dezelfde basis zijn gerangschikt.`,
    momentumHow: (substitution) => `Koers één maand geleden ÷ koers twaalf maanden geleden − 1${substitution}\n\nDe meest recente maand wordt bewust uitgesloten: die vertoont mean reversion. Opname ervan maakt een gewoon twaalfmaandsrendement tot een zwak momentumsignaal.`,
    volHow: (pct) => `std(maandrendement, ddof=1) × √12 = ${pct}\n\nOnze eigen yfinance-slotkoersen, op elke datum omgerekend naar EUR — inclusief de valutabeweging die een eurobelegger werkelijk ondervindt.`,
    betaHow: (benchmark, beta) => `cov(instrument, ${benchmark}) ÷ var(${benchmark}) = ${beta}\n\nWekelijkse EUR-rendementen over de laatste vijf jaar, voor weken waarin beide reeksen bestaan. Wekelijks omdat de benchmarktracker en een Amerikaanse notering vijf uur na elkaar sluiten, waardoor dagelijkse correlatie kunstmatig wordt gehalveerd.`,
    volMissing: 'Een streepje is geen nul — 0,0% zou uitzonderlijke stabiliteit betekenen.',
    betaMissing: 'Een streepje is geen nul — 0 zou betekenen dat de positie onafhankelijk van de markt beweegt.',
    volMissingWhat: (name) => `${name} heeft minder dan vier jaar koershistorie en daarom geen vijfjaarsvolatiliteit.`,
    volWhat: (name) => `Hoe sterk de koers van ${name} op jaarbasis bewoog over de laatste vijf jaar.`,
    betaMissingWhat: (name, benchmark) => `${name} heeft te weinig overlappende historie met ${benchmark} om bèta te meten.`,
    betaWhat: (name, benchmark) => `Hoe sterk ${name} beweegt bij elke 1% beweging van ${benchmark}.`,
    betaNote: (benchmark) => `wekelijkse EUR-rendementen versus ${benchmark}, 5 jaar`,
    weightWhat: (name) => `Het HUIDIGE aandeel van ${name} in het boek.`,
    weightNote: 'Huidige waarde ÷ totale Huidige waarde van het boek',
    yfFallback: 'yfinance, niet AIRS — voor deze rij zijn geen AIRS-boekwaarden beschikbaar (het onderliggende model heeft geen gekoppeld boek of nergens een beginwaarde), dus er is geen boekcijfer om te tonen.',
    interpolated: 'Beginkoers geïnterpoleerd — geen slotkoers nabij het begin van de periode',
    noEndValue: 'aan één einde van de periode ontbreekt een waardering — een streepje, nooit 0%, want “niet prijsbaar” en “niet bewogen” zijn verschillende feiten',
    priorYear: (value) => `${value} van het gerealiseerde resultaat van deze positie is in EERDERE jaren verdiend en hoort terecht niet bij het cijfer van dit jaar.`,
    moneyLookthroughWhat: (book, name) => `Wat ${book} verdiende op het geld dat het in ${name} belegde; dit boek houdt de positie via een certificaat aan.`,
    moneyDirectWhat: (name) => `Het rendement van ${name} op het werkelijk belegde geld.`,
    moneyViaWhat: (certificate) => `Aangehouden via ${certificate}, waarin de aankopen plaatsvinden; deze onderliggende positie heeft geen eigen aankopen.`,
    moneyCashWhat: 'Liquiditeiten worden niet gekocht en verkocht; er is daarom geen belegd kapitaal om rendement tegen af te zetten.',
    moneyUnknownWhat: (name) => `Het rendement van ${name} op het belegde geld kan niet worden berekend.`,
    lookthroughHow: (book, capital, pct, name, certificate, slice) => `Resultaat ÷ gemiddeld belegd kapitaal, gemeten in ${book}\n\n${capital} gemiddeld belegd kapitaal daar → ${pct}\n\nDit boek kocht ${certificate}, niet ${name}. Dit is wat ${book} op het eigen geld verdiende; uw timing in het certificaat telt niet mee. De ${slice} ernaast is uw aandeel in de positie. Schalen van teller en noemer verandert het rendement niet.`,
    noTransactionsHow: (reason) => `Resultaat ÷ gemiddeld belegd kapitaal\n\ngeen noemer — ${reason} Met deze positie is niets mis; alle andere kolommen blijven ongewijzigd.`,
    depositedHow: 'Resultaat ÷ gemiddeld belegd kapitaal\n\ngeweigerd — gedurende het jaar zijn aandelen gestort (splitsing, bonusaandeel of overdracht), waardoor handels- en positieaantallen verschillende grondslagen gebruiken. Het belegde kapitaal kan niet worden afgeleid; de eurokolommen blijven geldig.',
    viaHow: (name, certificate, routes, pct, capital) => `Resultaat ÷ gemiddeld belegd kapitaal\n\ngeen noemer voor ${name}: AIRS handelt ${certificate}${routes} in plaats van de onderliggende instrumenten, dus deze positie heeft geen eigen aankopen.\n\nHet certificaat is wel meetbaar: ${pct} over ${capital} gemiddeld belegd kapitaal. Dat is één cijfer voor het omhulsel, niet voor dit aandeel zelf.`,
    cashHow: 'Resultaat ÷ gemiddeld belegd kapitaal\n\nniet van toepassing — liquiditeiten worden niet gekocht en verkocht. Het rendement is per definitie 0% en het effect zit al in de categorie- en boektotalen.',
    genericNoCapitalHow: 'Resultaat ÷ gemiddeld belegd kapitaal\n\ngeen noemer — deze positie wordt via een certificaat bereikt dat AIRS verhandelt in plaats van de onderliggende instrumenten.',
    returnMissingWhat: (name) => `${name} kon over deze periode niet worden geprijsd.`,
    returnWhat: (name, from) => `Het EUR-rendement van ${name} sinds ${from}.`,
    yfReturnNote: 'onze eigen EUR-slotkoersreeks — geen AIRS-boek waardeert deze rij',
    contributionMissingWhat: (name) => `${name} heeft geen bijdragend resultaat omdat de positie over de periode niet kon worden gewaardeerd.`,
    contributionWhat: (name) => `Wat ${name} aan het jaarrendement van het boek toevoegde of ervan aftrok.`,
    noContributionHow: 'Resultaat ÷ beginkapitaal van het boek\n\ngeen resultaat — de positie kon niet aan beide uiteinden van de periode worden gewaardeerd, dus er is niets om te delen',
    weightHow: (value, total, pct) => `Huidige waarde ÷ totale Huidige waarde van het boek\n\n${value} ÷ ${total} = ${pct}`,
    fundamentalTitle: (name) => `Fundamenteel — is ${name} fundamenteel sterk? (owner earnings + koersstabiliteit)`,
    timingTitle: (name) => `Waarom de handel in ${name} verschil maakte`,
    heldDirectly: 'rechtstreeks aangehouden', atOpen: 'bij aanvang', netDividend: 'nettodividend',
    strategyBehindCertificate: 'de strategie achter het certificaat', certificate: 'een certificaat',
    childBook: 'het onderliggende boek', theCertificate: 'het certificaat',
    noTransactions: 'dit boek heeft geen leesbare transacties, dus er zijn geen kasstromen om het kapitaal mee te wegen.',
    soldRiskPrice: (isin) => `Voor ${isin} is geen koersreeks opgeslagen; de risicocijfers van dit instrument kunnen daarom niet worden berekend.`,
    soldRiskIdentity: (name) => `“${name}” kon niet aan een ISIN worden gekoppeld. Geen boek met een momentopname houdt het nog aan en er is geen handmatige koppeling; er is daarom geen instrument om te meten.`,
    blendNote: (count) => `${count} routes naar de positie, elk gewaardeerd door het boek dat deze aanhoudt en gewogen naar beginwaarde`,
    blendHow: (math) => `Σ (aandeel van elke route in deze positie × eigen rendement van die route)\n\n${math}`,
    yfReturnHow: (pct, from) => `onze eigen EUR-slotkoersreeks — geen AIRS-boekwaarden voor deze rij\n\n${pct} sinds ${from}`,
    bookReturnHow: (math, pct, valuedBy) => `(Huidige waarde + netto-inkomsten) ÷ Beginwaarde − 1${valuedBy ? `, gewaardeerd door ${valuedBy}` : ''}\n\n${math} = ${pct}`,
    routeTitle: (label, bookPct, value, rowPct) => `${label}: ${bookPct}% van het boek · ${value}${rowPct ? ` · ${rowPct}% van deze positie` : ''}`,
  },
  classRow: {
    fundamentalTitle: (count, bucket) => `Samengevoegde owner earnings en koersstabiliteit over de ${count} geprijsde positie${count === 1 ? '' : 's'} in ${bucket}, gewogen naar het huidige boekbelang.`,
    weightWhat: (bucket) => `Het HUIDIGE aandeel van ${bucket} in het boek.`,
    chartWeightNote: 'het eigen cijfer uit de allocatiegrafiek — inclusief liquiditeiten', rowsWeightNote: 'opgeteld uit de rijen hieronder',
    moneyWhat: (bucket) => `Het rendement van ${bucket} op het werkelijk belegde geld.`,
    coverageTitle: (pct, bucket, missing) => `Dit rendement dekt ${pct}% van wat ${bucket} verdiende. ${missing} positie(s) hadden geen waarde aan het begin van het jaar en daardoor geen rendementsnoemer. Hun euro's blijven in Resultaat staan.`,
    noReturn: (bucket) => `Niets in ${bucket} werd aan het begin van het jaar aangehouden; er is daarom geen rendement om te meten.`,
    returnWhat: (bucket) => `Wat ${bucket} dit jaar verdiende ten opzichte van de waarde aan het begin van het jaar.`,
    contributionWhat: (bucket) => `Wat ${bucket} aan het jaarrendement van het boek toevoegde of ervan aftrok.`,
    dashNote: 'een streepje, nooit 0% — “geen startkapitaal om tegen af te zetten” en “niet bewogen” zijn verschillende feiten',
    moneyHow: (result, capital, pct, covered, total) => `Resultaat ÷ gemiddeld belegd kapitaal\n\n${result} ÷ ${capital} = ${pct}${covered < total ? ` (over ${covered} van de ${total} posities die het boek zelf koopt en verkoopt; de rest zit in certificaten zonder eigen kasstromen)` : ''}`,
    returnHow: (result, opening, pct) => `Resultaat ÷ waarde van deze categorie aan het begin van het jaar\n\n${result} ÷ ${opening} = ${pct}`,
    returnNote: (result, opening, coverage) => `${result} ÷ ${opening}${coverage ? ` · dekt ${coverage}% van wat deze categorie verdiende` : ''}`,
    contributionNote: (result) => `${result} ÷ beginkapitaal van het boek`,
    contributionHow: (ret, share, opening, basis, contribution) => `Rendement × aandeel van deze categorie in het beginkapitaal van het boek\n\n${ret} × ${share} (${opening} van ${basis}) = ${contribution}`,
    weightHow: (pct) => `Σ Huidige waarde van deze categorie ÷ boektotaal\n\n${pct} — hetzelfde cijfer als in de allocatiebalk hierboven`,
  },
  sold: {
    soldOut: 'gedurende het jaar volledig verkocht', priorYear: 'vorig jaar',
    moneyWhat: (name) => `Het rendement van ${name} op het belegde geld gedurende het deel van het jaar waarin de positie werd aangehouden.`,
    contributionWhat: (name) => `Wat ${name} vóór verkoop aan het boekrendement toevoegde of ervan aftrok.`,
    momentumTitle: (name) => `12-1-momentum van ${name}, gemeten tot vandaag en niet tot de verkoopdatum, op dezelfde grondslag als aangehouden posities.`,
    volTitle: (name) => `Geannualiseerde vijfjaarsvolatiliteit van ${name} in EUR, gemeten tot vandaag.`,
    betaTitle: (name, benchmark) => `Vijfjaarsbèta van ${name} tegenover ${benchmark}, op wekelijkse EUR-rendementen.`,
  },
  reconciliation: {
    positions: (count) => `${count} posities, alles wat werd aangehouden of verkocht`,
    compareHow: (contribution, book, agrees) => `AIRS' eigen cumulatief_rendement tegenover het totaal Bijdrage\n\n${contribution} uit deze rijen versus ${book} uit AIRS — ze ${agrees ? 'komen overeen' : 'komen NIET overeen'}`,
    success: (book) => `✓ Deze posities verklaren het hele jaar — Bijdrage telt exact op tot AIRS' ${book}.`,
    mismatch: (sum, book, residual) => `⚠ Bijdrage telt op tot ${sum} tegenover AIRS' ${book}; ${residual} van het jaar wordt niet door deze rijen verklaard.`,
  },
  coverageWarning: (priced, total, pct, missing) => {
    const head = `⚠ Deze index is herbouwd uit ${priced} van de ${total} constituenten (${pct}); de wegingen zijn over het resterende deel herwogen.`;
    if (!missing.length) return `${head} Beschouw de afwijkingen als indicatief.`;
    const where = missing.map((m) => `${m.country} (${m.members - m.missing} van ${m.members})`).join(', ');
    return `${head} Het gat is NIET gelijkmatig verdeeld — het zit vooral in ${where}. Regionale afwijkingen ten opzichte van deze benchmark zijn het minst betrouwbare deel van de grafiek.`;
  },
  serverText: (text) => text
    .replace('No Dynamic portfolio is paired with this one, so there are no transactions to read — a model is a set of weights; only a book trades.', 'Er is geen dynamische portefeuille aan gekoppeld, dus er zijn geen transacties om te lezen — een model is een set wegingen; alleen een boek handelt.')
    .replace(/Could not read this book's transactions \(([^)]+)\)\./, 'De transacties van dit boek konden niet worden gelezen ($1).')
    .replace("This book's transactions have not been fetched yet, so what it realised on sales is unknown.", 'De transacties van dit boek zijn nog niet opgehaald; het gerealiseerde verkoopresultaat is daarom onbekend.')
    .replace(/The positions are valued at (.+) and AIRS's result runs to (.+), so this difference is most likely the market moving in between — not a missing position\. Re-scan the book to line the dates up\./, 'De posities zijn gewaardeerd op $1 en het AIRS-resultaat loopt tot $2. Het verschil komt waarschijnlijk door marktbeweging tussen beide datums en niet door een ontbrekende positie. Scan het boek opnieuw om de datums gelijk te trekken.')
    .replace('Both sides are valued on the same date, so this is genuinely unexplained by the positions — a leg is missing.', 'Beide zijden zijn op dezelfde datum gewaardeerd; het verschil wordt dus werkelijk niet door de posities verklaard — er ontbreekt een component.')
    .replace('This model portfolio is not paired with an AIRS book, so there are no valued holdings to show.', 'Deze modelportefeuille is niet aan een AIRS-boek gekoppeld; er zijn daarom geen gewaardeerde posities om te tonen.'),
};

export const ANALYSE_COPY: Record<Lang, AnalyseCopy> = { en, nl };

export function useAnalyseCopy(): AnalyseCopy {
  const [lang] = useLang();
  return ANALYSE_COPY[lang];
}
