-- Confirmed corporate actions are deliberately separate from stale-price
-- detection: a takeover must be acted on at its effective date, not after a
-- generic 15-trading-day inactivity threshold.
CREATE TABLE IF NOT EXISTS public.corporate_action (
    corporate_action_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id integer NOT NULL REFERENCES public.company(company_id),
    action_type text NOT NULL CHECK (action_type IN ('takeover', 'delisting', 'spinoff')),
    effective_date date NOT NULL,
    last_tradable_date date,
    cash_per_share numeric,
    successor_company_id integer REFERENCES public.company(company_id),
    successor_shares_per_share numeric,
    source_url text NOT NULL,
    note text,
    confirmed_at timestamptz NOT NULL DEFAULT now(),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, action_type, effective_date)
);

CREATE INDEX IF NOT EXISTS corporate_action_effective_idx
    ON public.corporate_action (effective_date, company_id);

-- A rebalance must retain enough of its contemporaneous ranking to replace a
-- subsequently untradable holding without re-scoring the current universe.
ALTER TABLE public.current_picks_snapshot
    ADD COLUMN IF NOT EXISTS selection_reserves jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE TABLE IF NOT EXISTS public.scheduled_strategy_forced_replacement (
    forced_replacement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheduled_strategy_id integer NOT NULL REFERENCES public.scheduled_strategy(id),
    rebalance_snapshot_id integer NOT NULL REFERENCES public.current_picks_snapshot(snapshot_id),
    corporate_action_id bigint NOT NULL REFERENCES public.corporate_action(corporate_action_id),
    removed_company_id integer NOT NULL REFERENCES public.company(company_id),
    replacement_company_id integer REFERENCES public.company(company_id),
    effective_date date NOT NULL,
    target_weight double precision NOT NULL CHECK (target_weight > 0 AND target_weight <= 1),
    reserve_rank integer,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied', 'cash')),
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    applied_at timestamptz,
    UNIQUE (scheduled_strategy_id, rebalance_snapshot_id, corporate_action_id, removed_company_id)
);

CREATE INDEX IF NOT EXISTS scheduled_strategy_forced_replacement_pending_idx
    ON public.scheduled_strategy_forced_replacement (status, effective_date);

-- Confirmed Nasdaq corporate-action notice ECA2026-702.  The SELECT makes
-- this safe on a database where Qorvo has not been ingested yet; a later
-- admin action can add it once the company row exists.
INSERT INTO public.corporate_action (
    company_id, action_type, effective_date, last_tradable_date,
    cash_per_share, successor_company_id, successor_shares_per_share,
    source_url, note
)
SELECT q.company_id, 'takeover', DATE '2026-10-06', DATE '2026-10-02',
       32.50, s.company_id, 0.960,
       'https://www.nasdaqtrader.com/TraderNews.aspx?id=ECA2026-702',
       'Qorvo merger with Skyworks; confirmed by Nasdaq corporate-action notice.'
FROM public.company AS q
LEFT JOIN public.company AS s ON s.gurufocus_ticker = 'SWKS'
WHERE q.isin = 'US74736K1016'
ON CONFLICT (company_id, action_type, effective_date) DO NOTHING;
