CREATE TABLE IF NOT EXISTS public.bc_log_entry (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_date date NOT NULL DEFAULT CURRENT_DATE,
  company_name text NOT NULL,
  isin text NOT NULL,
  decision text NOT NULL,
  notes text NOT NULL DEFAULT '',
  actions text NOT NULL DEFAULT '',
  conviction integer NOT NULL CHECK (conviction BETWEEN 1 AND 5),
  portfolio_weight numeric,
  flag text NOT NULL DEFAULT 'none' CHECK (flag IN ('none', 'yellow', 'red')),
  review_on date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS bc_log_entry_meeting_date_idx ON public.bc_log_entry (meeting_date DESC);
NOTIFY pgrst, 'reload schema';
